aws_region                = "ap-south-1"
name_prefix="demo-ecs_fargate"
cidr_block            = "192.168.0.0/16"
environment               = "dev"
public_subnet_cidrs       = ["192.168.1.0/24", "192.168.2.0/24"]
private_subnet_cidrs      = ["192.168.101.0/24", "192.168.102.0/24"]
alb_name                  = "demo-apps-alb"
ecs_cluster_name          = "demo-ecs-cluster"
task_family_patient       = "demo-task-patient"
task_family_appointment   = "demo-task-appointment"
patient_service_image     = "211125325699.dkr.ecr.ap-south-1.amazonaws.com/demo-ecs-patitent-service:latest"
appointment_service_image = "211125325699.dkr.ecr.ap-south-1.amazonaws.com/demo-ecs-appointment-service:latest"
log_group_name            = "ecs-cluster-logs"
service_name_patitent     = "demo-ecs-patitent"
service_name_appointment  = "demo-ecs-appointment"
ecs_execution_role_name   = "ecs-execution-role"
ecs_task_role_name        = "ecs-task-role"
availability_zones= ["ap-south-1a", "ap-south-1b"]
